package common;

//@author A0097282W
public enum InvalidCommandReason {
	UNRECOGNIZED_COMMAND,
	TOO_FEW_ARGUMENTS,
	EMPTY_COMMAND,
	INVALID_TASK_INDEX,
	INVALID_TIMESLOT_INDEX,
	INVALID_PAGE_INDEX,
	INVALID_SEARCH_PARAMETERS,
	INVALID_DATE
}
